export default {
    debug: false,
    token: "",
    username: "",
    isRealm: false,
    realmInviteCode: "",
    ip: "",
    port: 19132,
    guild: "",
    channel: "",
    ParadoxEnabled: true,
    paradoxLogsChannel: "",
    cmdPrefix: "!",
    useSystemPlayerJoinMessage: false,
    logSystemCommands: false,
    systemCommandsChannel: "",
    sendWhisperMessages: false,

    useEmbed: true,
    setColor: [0, 153, 255] as const,
    setTitle: "My Servers Name!",
    AuthType: false,
    admins: [""],
    blacklistDeviceTypes: [],
};
